### ISSUE TITLE
Date picker doesn't work

### ISSUE THREAD

**Issue by giutrec** [AssociazionePrometeo/gianomanager#19]
From #17  the date picker does not work

**Comment by mattbit** [comment]
Working on it in  #13

**Comment by mattbit** [comment]
### Useful links
- [FullCalendar](https://fullcalendar.io/js/fullcalendar-3.4.0/demos/selectable.html) see the week view
- [Kendo UI scheduler](http://demos.telerik.com/kendo-ui/scheduler/index)

**Comment by giutrec** [comment]
another link
 https://codepen.io/yangg/pen/aOmGJd

Kendo UI schedular is the nicest!

**Comment by mattbit** [comment]
We will first implement the standard datepicker using [flatpickr](https://chmln.github.io/flatpickr/) for the datetime inputs. The component to select reservation intervals will be implemented later.
