### ISSUE TITLE
View rule for fixed admin e default 

### ISSUE THREAD

**Issue by fdaluisio** [AssociazionePrometeo/gianomanager#41]
In Admin -> Roles we need to show the applyed role for Admin and Default role group to allow the user to have a better understanding of GianoManager

**Comment by mattbit** [comment]
Not sure I understood correctly. Do you mean we should show the permissions for the admin & default groups?

**Comment by fdaluisio** [comment]
Yes, greyed box (not editable page) like the edit page

**Comment by mattbit** [comment]
Great, will do this later today.

**Comment by giutrec** [comment]
the #43 close this
