### ISSUE TITLE
User must change his email address?

### ISSUE THREAD

**Issue by fdaluisio** [AssociazionePrometeo/gianomanager#53]
Edit-> Profile with a User in Default Role.

He can change his email and not his name.
It would be best if email change was followed by the admin role while the user can change his name as he likes.
Action: Remove the grayed Name in User Profile and force greyed email address for the profile of user.

**Comment by fdaluisio** [comment]
Another simple request:
In Edit->Profile the flag active must be much more visible and placed at the top of the page

**Comment by giutrec** [comment]
The name is set for the user because it is tied to the single person, it is not editable and should not be.
 If you want to change name means you are another person and then you are making a new user.

**Comment by giutrec** [comment]
partially closed with #62
